# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jadenfix/financial_cpp_copy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jadenfix/financial_cpp_copy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jadenfix/financial_cpp_copy/CMakeFiles /Users/jadenfix/financial_cpp_copy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jadenfix/financial_cpp_copy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trading_system_lib

# Build rule for target.
trading_system_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trading_system_lib
.PHONY : trading_system_lib

# fast build rule for target.
trading_system_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system_lib.dir/build.make CMakeFiles/trading_system_lib.dir/build
.PHONY : trading_system_lib/fast

#=============================================================================
# Target rules for targets named trading_system

# Build rule for target.
trading_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trading_system
.PHONY : trading_system

# fast build rule for target.
trading_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/build
.PHONY : trading_system/fast

#=============================================================================
# Target rules for targets named test_integrity

# Build rule for target.
test_integrity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integrity
.PHONY : test_integrity

# fast build rule for target.
test_integrity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integrity.dir/build.make CMakeFiles/test_integrity.dir/build
.PHONY : test_integrity/fast

#=============================================================================
# Target rules for targets named strategy_perf_test

# Build rule for target.
strategy_perf_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strategy_perf_test
.PHONY : strategy_perf_test

# fast build rule for target.
strategy_perf_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strategy_perf_test.dir/build.make CMakeFiles/strategy_perf_test.dir/build
.PHONY : strategy_perf_test/fast

src/data/DataManager.o: src/data/DataManager.cpp.o
.PHONY : src/data/DataManager.o

# target to build an object file
src/data/DataManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system_lib.dir/build.make CMakeFiles/trading_system_lib.dir/src/data/DataManager.cpp.o
.PHONY : src/data/DataManager.cpp.o

src/data/DataManager.i: src/data/DataManager.cpp.i
.PHONY : src/data/DataManager.i

# target to preprocess a source file
src/data/DataManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system_lib.dir/build.make CMakeFiles/trading_system_lib.dir/src/data/DataManager.cpp.i
.PHONY : src/data/DataManager.cpp.i

src/data/DataManager.s: src/data/DataManager.cpp.s
.PHONY : src/data/DataManager.s

# target to generate assembly for a file
src/data/DataManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system_lib.dir/build.make CMakeFiles/trading_system_lib.dir/src/data/DataManager.cpp.s
.PHONY : src/data/DataManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

strategy_performance_test.o: strategy_performance_test.cpp.o
.PHONY : strategy_performance_test.o

# target to build an object file
strategy_performance_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strategy_perf_test.dir/build.make CMakeFiles/strategy_perf_test.dir/strategy_performance_test.cpp.o
.PHONY : strategy_performance_test.cpp.o

strategy_performance_test.i: strategy_performance_test.cpp.i
.PHONY : strategy_performance_test.i

# target to preprocess a source file
strategy_performance_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strategy_perf_test.dir/build.make CMakeFiles/strategy_perf_test.dir/strategy_performance_test.cpp.i
.PHONY : strategy_performance_test.cpp.i

strategy_performance_test.s: strategy_performance_test.cpp.s
.PHONY : strategy_performance_test.s

# target to generate assembly for a file
strategy_performance_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strategy_perf_test.dir/build.make CMakeFiles/strategy_perf_test.dir/strategy_performance_test.cpp.s
.PHONY : strategy_performance_test.cpp.s

test_data_integrity.o: test_data_integrity.cpp.o
.PHONY : test_data_integrity.o

# target to build an object file
test_data_integrity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integrity.dir/build.make CMakeFiles/test_integrity.dir/test_data_integrity.cpp.o
.PHONY : test_data_integrity.cpp.o

test_data_integrity.i: test_data_integrity.cpp.i
.PHONY : test_data_integrity.i

# target to preprocess a source file
test_data_integrity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integrity.dir/build.make CMakeFiles/test_integrity.dir/test_data_integrity.cpp.i
.PHONY : test_data_integrity.cpp.i

test_data_integrity.s: test_data_integrity.cpp.s
.PHONY : test_data_integrity.s

# target to generate assembly for a file
test_data_integrity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integrity.dir/build.make CMakeFiles/test_integrity.dir/test_data_integrity.cpp.s
.PHONY : test_data_integrity.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... strategy_perf_test"
	@echo "... test_integrity"
	@echo "... trading_system"
	@echo "... trading_system_lib"
	@echo "... src/data/DataManager.o"
	@echo "... src/data/DataManager.i"
	@echo "... src/data/DataManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... strategy_performance_test.o"
	@echo "... strategy_performance_test.i"
	@echo "... strategy_performance_test.s"
	@echo "... test_data_integrity.o"
	@echo "... test_data_integrity.i"
	@echo "... test_data_integrity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

